Set-Alias fs FuzzySearch
Set-Alias fo Start-SearchedFile
Set-Alias fp Get-SearchedFile
Set-Alias fe Edit-SearchedFile
Set-Alias c Clear-Palette
Set-Alias papp PinApp
Set-Alias purl PinURLandFile
Set-Alias wb Start-Website
Set-Alias ws WebSearch
Set-Alias o Start-Process
Set-Alias rh Restart-Palette
Set-Alias np Set-TemporaryHistory
Set-Alias yp Set-PaletteHistory
Set-Alias nnt New-Note
Set-Alias gnt Get-Note